version: '3.1'

services:

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_USERNAME: "{{USERNAME}}"
      MONGODB_PASSWORD: "{{ PASSWORD }}"
      MONGODB_NAME: "{{DATABASENAME}}"